# [unstable]
#   # enable the unstable artifact-dependencies feature, see
#   # https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#artifact-dependencies
#   bindeps = true

# [target.x86_64-unknown-none]
#   rustflags = [
#     "-C",
#     "-C",
#     "-C",
#     "-C",
#     "-C",
#     "-g",
#     "force-frame-pointers=yes",
#     "force-unwind-tables=yes",
#     "link-arg=-z",
#     "link-arg=nostart-stop-gc",
#     "relocation-model=static",
#   ]

[unstable]
  build-std          = ["compiler_builtins", "core"]
  build-std-features = ["compiler-builtins-mem"]

[build]
  target = "x86_64-oreos.json"

[target.'cfg(target_os = "none")']
  runner = "bootimage runner"
